version: 2

project_name: heimdall

builds:
  - id: heimdall
    main: .
    binary: heimdall
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/BetterCallB4RB4/heimdall/cmd.version={{ .Version }}

archives:
  - id: heimdall
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
